# rename this file to config.yaml before start

# qqbot account, not needed anymore for qrcode authentication
account:  12345678
password: "123"

# server to view verification code, not required for mac
port: 3100
host: localhost

# message handling, ignore offline message 20 min ago
# offline_msg_keeptime: 1200

# plugin list
plugins:
    # - help
    # - debug
    - chinobot
    # - hitokoto
    - apiserver
    - webhook

# apiserver plugin configration
api_port:  3200
api_token: 'xxxx'

webhook:
    url: 'http://localhost:3300/msg'

tuling_key: 'xxxxxxxx'
qq_group_id: 12345678